import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "./_components/Header";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-os",
});
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-pp",
});

export const metadata: Metadata = {
  title: "Blog of Elke",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${poppins.variable} bg-light font-poppins font-light tracking-wide dark:bg-dark`}
      >
        <Header />
        <main> {children}</main>
      </body>
    </html>
  );
}
